export const categoryData = [
  {
    name: "AI",
    description: "Latest in artificial intelligence - from LLMs to robotics",
    href: "/blog/category/ai",
    gradient: "from-violet-600/10 via-violet-900/5 to-transparent",
    border: "border-violet-800/20",
    hover: "hover:border-violet-600/40",
    icon: "🤖",
    color: "text-violet-400",
    bgGlow: "bg-violet-500/10",
  },
  {
    name: "Gaming",
    description: "Reviews, previews, and industry insights",
    href: "/blog/category/gaming",
    gradient: "from-emerald-600/10 via-emerald-900/5 to-transparent",
    border: "border-emerald-800/20",
    hover: "hover:border-emerald-600/40",
    icon: "🎮",
    color: "text-emerald-400",
    bgGlow: "bg-emerald-500/10",
  },
  {
    name: "Esports",
    description: "Tournaments, teams, and competitive play",
    href: "/blog/category/esports",
    gradient: "from-amber-600/10 via-amber-900/5 to-transparent",
    border: "border-amber-800/20",
    hover: "hover:border-amber-600/40",
    icon: "🏆",
    color: "text-amber-400",
    bgGlow: "bg-amber-500/10",
  },
  {
    name: "Tech",
    description: "Hardware, software, and emerging trends",
    href: "/blog/category/tech",
    gradient: "from-sky-600/10 via-sky-900/5 to-transparent",
    border: "border-sky-800/20",
    hover: "hover:border-sky-600/40",
    icon: "💻",
    color: "text-sky-400",
    bgGlow: "bg-sky-500/10",
  },
]