import { NextResponse } from "next/server";

const agents = [
  {
    id: 1,
    name: "CodeAssist Pro",
    slug: "codeassist-pro",
    description: "AI-powered code completion and refactoring assistant.",
    type: "review",
    rating: 4.8,
    pros: ["Fast autocomplete", "Accurate suggestions", "Great DX"],
    cons: ["Expensive", "Requires internet"],
    pricing: "$20/mo",
    category: "Coding",
  },
  {
    id: 2,
    name: "WriteMind",
    slug: "writemind",
    description: "Generative writing agent for blogs and documentation.",
    type: "review",
    rating: 4.5,
    pros: ["Natural output", "Tone customization"],
    cons: ["Occasional hallucinations", "Slow on long text"],
    pricing: "$15/mo",
    category: "Writing",
  },
  {
    id: 3,
    name: "DataSift",
    slug: "datasift",
    description: "Automated data analysis and visualization agent.",
    type: "news",
    rating: 4.3,
    pros: ["Handles large datasets", "Beautiful charts"],
    cons: ["Limited integrations", "Steep learning curve"],
    pricing: "$30/mo",
    category: "Data",
  },
  {
    id: 4,
    name: "DevOpsBot",
    slug: "devopsbot",
    description: "AI agent that monitors and manages CI/CD pipelines.",
    type: "review",
    rating: 4.6,
    pros: ["Proactive alerts", "Easy setup"],
    cons: ["No on-prem option", "Beta features unstable"],
    pricing: "$25/mo",
    category: "DevOps",
  },
  {
    id: 5,
    name: "DesignGenius",
    slug: "designgenius",
    description: "Generates UI mockups and design systems from prompts.",
    type: "news",
    rating: 4.2,
    pros: ["Quick prototyping", "Figma export"],
    cons: ["Limited component library", "Subscription tier lock"],
    pricing: "Free / $18 Pro",
    category: "Design",
  },
  {
    id: 6,
    name: "TestPilot",
    slug: "testpilot",
    description: "Autonomous testing agent that writes and runs unit tests.",
    type: "review",
    rating: 4.7,
    pros: ["Saves hours", "High coverage"],
    cons: ["Flaky on legacy code", "JS/TS only"],
    pricing: "$35/mo",
    category: "Testing",
  },
  {
    id: 7,
    name: "DocuWeaver",
    slug: "docuweaver",
    description: "Auto-generates technical documentation from codebases.",
    type: "review",
    rating: 4.4,
    pros: ["Supports many languages", "Wiki export"],
    cons: ["Needs cleanup", "No video output"],
    pricing: "$12/mo",
    category: "Documentation",
  },
  {
    id: 8,
    name: "SecurityShield",
    slug: "securityshield",
    description: "AI vulnerability scanner for dependencies and infra.",
    type: "news",
    rating: 4.1,
    pros: ["Real-time scanning", "Detailed reports"],
    cons: ["False positives", "High memory usage"],
    pricing: "$40/mo",
    category: "Security",
  },
];

export async function GET() {
  return NextResponse.json(agents);
}
